# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8092
  port: 8092

spring:
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB

# 日志配置
logging:
  level:
    cn.zn: debug
    org.springframework: warn

baidu:
  client-id: 替换真实id
  client-secret: 替换真实secret
